In [1]:
# Import & Setup

import numpy as np
np.random.seed(42)

In [2]:
##Arrays

# 1D Array
a = np.array([1, 2, 3, 4])
print("1D Array:", a)

# 2D Array
b = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", b)

# Zeros and Ones
zeros = np.zeros((2, 3))
ones = np.ones((3, 3))

print("Zeros:\n", zeros)
print("Ones:\n", ones)

1D Array: [1 2 3 4]
2D Array:
 [[1 2 3]
 [4 5 6]]
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [3]:
# Array Operations

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])


print("Addition:", x + y)
print("Multiplication:", x * y)
print("Mean:", np.mean(x))
print("Standard Deviation:", np.std(x))

Addition: [5 7 9]
Multiplication: [ 4 10 18]
Mean: 2.0
Standard Deviation: 0.816496580927726


In [5]:
# Matrix Multiplication (how neural networks compute forward pass.)

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Method 1
result1 = np.dot(A, B)

# Method 2
result2 = A @ B

print("Shape of A:", A.shape)
print("Shape of B:", B.shape)
print("Matrix Multiplication (dot):\n", result1)
print("Matrix Multiplication (@):\n", result2)


Shape of A: (2, 2)
Shape of B: (2, 2)
Matrix Multiplication (dot):
 [[19 22]
 [43 50]]
Matrix Multiplication (@):
 [[19 22]
 [43 50]]


In [ ]:
# Matrix multiplication is used in neural networks to compute the weighted sum of inputs.
# Every forward pass in a neural network is essentially a series of matrix multiplications.

In [11]:
# Broadcasting

a = np.array([1, 2, 3])
b = 2

print("Broadcasting result:", a * b)


Broadcasting result: [2 4 6]


In [12]:
# Vectorization

arr = np.array([1, 2, 3, 4])

result = []
for i in arr:
    result.append(i * 2)

print("Loop result:", result)

Loop result: [np.int64(2), np.int64(4), np.int64(6), np.int64(8)]


In [13]:
# Vectorized, fast

result_vec = arr * 2
print("Vectorized result:", result_vec)

Vectorized result: [2 4 6 8]


In [14]:
# Performance Comparison

import time

large_array = np.random.rand(1000000)

# Loop
start = time.time()
res_loop = [i * 2 for i in large_array]
print("Loop time:", time.time() - start)

# Vectorized
start = time.time()
res_vec = large_array * 2
print("Vectorized time:", time.time() - start)

Loop time: 0.06449007987976074
Vectorized time: 0.0007653236389160156


In [ ]:
# What is Vectorization? 
# Vectorization allows operations on entire arrays without explicit loops, making computations faster and efficient.

In [ ]:
### Why Vectorization is Important

# Vectorization eliminates Python loops and uses optimized low-level implementations (C/C++).
# This makes computations significantly faster and scalable for large datasets.

# In machine learning, vectorization is critical because models operate on large datasets,
# and inefficient loops can slow down training drastically.

In [7]:
# Mini ML Concept 

# Simulating a simple linear model: y = Wx + b

X = np.array([[1, 2], [3, 4]]) # features
W = np.array([[0.5], [1.0]]) # weight
b = 0.1 # bias

y = X @ W + b
print("Output:\n", y)

Output:
 [[2.6]
 [5.6]]


In [ ]:
# This demonstrates how machine learning models compute outputs using matrix multiplication.